package uz.apprica.plannote.ui.theme

import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.staticCompositionLocalOf

// ── AppStrings data class ─────────────────────────────────────────────────────

data class AppStrings(
    // ── Navigation ──────────────────────────────────────────────────────────
    val navHome: String,
    val navTasks: String,
    val navNotes: String,
    val navSettings: String,

    // ── Common ───────────────────────────────────────────────────────────────
    val save: String,
    val cancel: String,
    val add: String,
    val delete: String,
    val yes: String,
    val no: String,
    val days: String,
    val completed: String,
    val close: String,

    // ── Language screen ───────────────────────────────────────────────────────
    val selectLanguage: String,
    val selectLanguageDesc: String,
    val continueBtn: String,

    // ── Home ─────────────────────────────────────────────────────────────────
    val dailyInspiration: String,
    val todayTasks: String,
    val streak: String,
    val consecutive: String,
    val recordLabel: String,
    val detailsArrow: String,
    val todayMood: String,
    val selectMoodHint: String,
    val changeMood: String,
    val moodBad: String,
    val moodOk: String,
    val moodGood: String,
    val moodGreat: String,
    val moodSuper: String,

    // ── Tasks ────────────────────────────────────────────────────────────────
    val newTask: String,
    val taskNameHint: String,
    val taskNameRequired: String,
    val categoryLabel: String,
    val priorityLabel: String,
    val priorityLow: String,
    val priorityMedium: String,
    val priorityHigh: String,
    val noTasks: String,
    val noTasksHint: String,
    val taskCategories: List<String>,
    val taskDone: String,

    // ── Notes ─────────────────────────────────────────────────────────────────
    val notesTitle: String,
    val searchNotes: String,
    val newNote: String,
    val noteTitleHint: String,
    val noteContentHint: String,
    val noteColors: String,
    val pinnedLabel: String,
    val noNotes: String,
    val noNotesHint: String,

    // ── Settings ──────────────────────────────────────────────────────────────
    val settingsTitle: String,
    val darkMode: String,
    val darkModeOn: String,
    val darkModeOff: String,
    val resetStreak: String,
    val resetStreakCurrent: String,
    val resetStreakConfirmTitle: String,
    val resetStreakConfirmBody: String,
    val resetStreakConfirmYes: String,
    val resetStreakConfirmNo: String,
    val streakReset: String,
    val versionLabel: String,
    val developerLabel: String,
    val minAndroidLabel: String,
    val currentStreakLabel: String,
    val recordStreakLabel: String,
    val languageLabel: String,
    val languageChangeDesc: String,

    // ── Stats / Streak ────────────────────────────────────────────────────────
    val statistics: String,
    val weeklyResults: String,
    val weeklyMood: String,
    val noMoodYet: String,
    val overallStats: String,
    val weeklyTasks: String,
    val weeklyHabits: String,
    val noStats: String,
    val noStatsHint: String,
    val streakAndActivity: String,
    val lastSevenDays: String,
    val ketmaKet: String,
    val rekord: String,
    val weeklyTaskActivity: String,
    val habitTracker: String,

    // ── Extra stats labels ────────────────────────────────────────────────────
    val totalTasksLabel: String,
    val completionPctLabel: String,
    val activeHabitsLabel: String,
    val longestHabitStreakLabel: String,
    val allLabel: String,
    val activeLabel: String,
    val averageLabel: String,

    // ── Day abbreviations: Mon..Sun (index 0=Mon … 6=Sun) ─────────────────────
    val dayAbbreviations: List<String>
)

// ── Uzbek ─────────────────────────────────────────────────────────────────────

val uzStrings = AppStrings(
    navHome       = "Bosh",
    navTasks      = "Vazifalar",
    navNotes      = "Eslatmalar",
    navSettings   = "Sozlamalar",

    save          = "Saqlash",
    cancel        = "Bekor qilish",
    add           = "Qo'shish",
    delete        = "O'chirish",
    yes           = "Ha",
    no            = "Yo'q",
    days          = "kun",
    completed     = "bajarildi",
    close         = "Yopish",

    selectLanguage     = "Tilni tanlang",
    selectLanguageDesc = "Ilovada qaysi tilda ishlashni xohlaysiz?",
    continueBtn        = "Davom etish",

    dailyInspiration = "Kunlik ilhom",
    todayTasks       = "Bugungi vazifalar",
    streak           = "Ketma-ket streak",
    consecutive      = "Ketma-ket",
    recordLabel      = "Rekord",
    detailsArrow     = "Batafsil →",
    todayMood        = "Bugungi kayfiyat",
    selectMoodHint   = "Bugun kayfiyatingizni belgilang",
    changeMood       = "✏️  O'zgartirish",
    moodBad          = "Yomon",
    moodOk           = "O'rtacha",
    moodGood         = "Yaxshi",
    moodGreat        = "Ajoyib",
    moodSuper        = "Super!",

    newTask          = "Yangi vazifa",
    taskNameHint     = "Vazifa nomi *",
    taskNameRequired = "Nom kiritish shart!",
    categoryLabel    = "Kategoriya",
    priorityLabel    = "Muhimlik",
    priorityLow      = "Past",
    priorityMedium   = "O'rta",
    priorityHigh     = "Yuqori",
    noTasks          = "Bugun uchun vazifa yo'q",
    noTasksHint      = "+ tugmasi orqali vazifa qo'shing",
    taskCategories   = listOf("Ish", "Shaxsiy", "Salomatlik", "Ta'lim", "Boshqa"),
    taskDone         = "bajarildi",

    notesTitle    = "Eslatmalar",
    searchNotes   = "Eslatmalarni qidirish...",
    newNote       = "Yangi eslatma",
    noteTitleHint = "Sarlavha (ixtiyoriy)...",
    noteContentHint = "Fikrlaringizni yozing...",
    noteColors    = "Eslatma uchun ranglar",
    pinnedLabel   = "Pin qilingan",
    noNotes       = "Hali eslatma yo'q",
    noNotesHint   = "FAB orqali birinchi eslatmani qo'shing",

    settingsTitle          = "Sozlamalar",
    darkMode               = "Tungi rejim",
    darkModeOn             = "Qorong'i fon",
    darkModeOff            = "Yorug' fon",
    resetStreak            = "Streakni nollashtirish",
    resetStreakCurrent     = "Joriy",
    resetStreakConfirmTitle = "Streakni nollashtirish",
    resetStreakConfirmBody  = "o'chiriladi. Bu amalni qaytarib bo'lmaydi.",
    resetStreakConfirmYes   = "Ha, nollash",
    resetStreakConfirmNo    = "Bekor qilish",
    streakReset            = "Streak nollashtirildi ✓",
    versionLabel           = "Versiya",
    developerLabel         = "Ishlab chiquvchi",
    minAndroidLabel        = "Min. Android versiyasi",
    currentStreakLabel     = "Joriy streak",
    recordStreakLabel      = "Rekord streak",
    languageLabel          = "Til",
    languageChangeDesc     = "Ilova tili",

    statistics       = "Statistika",
    weeklyResults    = "Joriy hafta natijalari",
    weeklyMood       = "Haftalik kayfiyat",
    noMoodYet        = "Hali kayfiyat belgilanmagan. Home ekranidan belgilang!",
    overallStats     = "Umumiy statistika",
    weeklyTasks      = "Haftalik vazifalar",
    weeklyHabits     = "Haftalik odatlar",
    noStats          = "Statistika yo'q",
    noStatsHint      = "Odat yoki vazifa qo'shgandan keyin bu yerda ko'rinadi",
    streakAndActivity = "Streak va Faollik",
    lastSevenDays    = "So'nggi 7 kun",
    ketmaKet         = "Ketma-ket",
    rekord           = "Rekord",
    weeklyTaskActivity = "Haftalik vazifa faolligi",
    habitTracker     = "Odat tracker",

    totalTasksLabel        = "Jami vazifalar",
    completionPctLabel     = "Bajarilish %",
    activeHabitsLabel      = "Faol odatlar",
    longestHabitStreakLabel = "Eng uzun odat streak",
    allLabel               = "jami",
    activeLabel            = "aktiv",
    averageLabel           = "o'rtacha",
    dayAbbreviations       = listOf("Du", "Se", "Ch", "Pa", "Ju", "Sh", "Ya")
)

// ── Russian ───────────────────────────────────────────────────────────────────

val ruStrings = AppStrings(
    navHome       = "Главная",
    navTasks      = "Задачи",
    navNotes      = "Заметки",
    navSettings   = "Настройки",

    save          = "Сохранить",
    cancel        = "Отмена",
    add           = "Добавить",
    delete        = "Удалить",
    yes           = "Да",
    no            = "Нет",
    days          = "дн.",
    completed     = "выполнено",
    close         = "Закрыть",

    selectLanguage     = "Выберите язык",
    selectLanguageDesc = "На каком языке вы хотите использовать приложение?",
    continueBtn        = "Продолжить",

    dailyInspiration = "Вдохновение дня",
    todayTasks       = "Задачи на сегодня",
    streak           = "Серия дней",
    consecutive      = "Подряд",
    recordLabel      = "Рекорд",
    detailsArrow     = "Подробнее →",
    todayMood        = "Настроение сегодня",
    selectMoodHint   = "Отметьте своё настроение",
    changeMood       = "✏️  Изменить",
    moodBad          = "Плохо",
    moodOk           = "Средне",
    moodGood         = "Хорошо",
    moodGreat        = "Отлично",
    moodSuper        = "Супер!",

    newTask          = "Новая задача",
    taskNameHint     = "Название задачи *",
    taskNameRequired = "Введите название!",
    categoryLabel    = "Категория",
    priorityLabel    = "Приоритет",
    priorityLow      = "Низкий",
    priorityMedium   = "Средний",
    priorityHigh     = "Высокий",
    noTasks          = "Задач на сегодня нет",
    noTasksHint      = "Добавьте задачу через кнопку +",
    taskCategories   = listOf("Работа", "Личное", "Здоровье", "Учёба", "Другое"),
    taskDone         = "выполнено",

    notesTitle      = "Заметки",
    searchNotes     = "Поиск заметок...",
    newNote         = "Новая заметка",
    noteTitleHint   = "Заголовок (необязательно)...",
    noteContentHint = "Напишите свои мысли...",
    noteColors      = "Цвет заметки",
    pinnedLabel     = "Закреплённые",
    noNotes         = "Заметок пока нет",
    noNotesHint     = "Добавьте первую заметку через FAB",

    settingsTitle          = "Настройки",
    darkMode               = "Тёмный режим",
    darkModeOn             = "Тёмный фон",
    darkModeOff            = "Светлый фон",
    resetStreak            = "Сбросить серию",
    resetStreakCurrent     = "Текущая",
    resetStreakConfirmTitle = "Сбросить серию",
    resetStreakConfirmBody  = "будет удалена. Это действие нельзя отменить.",
    resetStreakConfirmYes   = "Да, сбросить",
    resetStreakConfirmNo    = "Отмена",
    streakReset            = "Серия сброшена ✓",
    versionLabel           = "Версия",
    developerLabel         = "Разработчик",
    minAndroidLabel        = "Мин. версия Android",
    currentStreakLabel     = "Текущая серия",
    recordStreakLabel      = "Рекорд серии",
    languageLabel          = "Язык",
    languageChangeDesc     = "Язык приложения",

    statistics        = "Статистика",
    weeklyResults     = "Результаты текущей недели",
    weeklyMood        = "Настроение за неделю",
    noMoodYet         = "Настроение не отмечено. Отметьте на главном экране!",
    overallStats      = "Общая статистика",
    weeklyTasks       = "Задачи за неделю",
    weeklyHabits      = "Привычки за неделю",
    noStats           = "Статистики нет",
    noStatsHint       = "Добавьте привычку или задачу, чтобы увидеть здесь данные",
    streakAndActivity = "Серия и Активность",
    lastSevenDays     = "Последние 7 дней",
    ketmaKet          = "Подряд",
    rekord            = "Рекорд",
    weeklyTaskActivity = "Активность задач за неделю",
    habitTracker      = "Трекер привычек",

    totalTasksLabel        = "Всего задач",
    completionPctLabel     = "Выполнение %",
    activeHabitsLabel      = "Активные привычки",
    longestHabitStreakLabel = "Лучшая серия привычки",
    allLabel               = "всего",
    activeLabel            = "активных",
    averageLabel           = "среднее",
    dayAbbreviations       = listOf("Пн", "Вт", "Ср", "Чт", "Пт", "Сб", "Вс")
)

// ── English ───────────────────────────────────────────────────────────────────

val enStrings = AppStrings(
    navHome       = "Home",
    navTasks      = "Tasks",
    navNotes      = "Notes",
    navSettings   = "Settings",

    save          = "Save",
    cancel        = "Cancel",
    add           = "Add",
    delete        = "Delete",
    yes           = "Yes",
    no            = "No",
    days          = "days",
    completed     = "completed",
    close         = "Close",

    selectLanguage     = "Select Language",
    selectLanguageDesc = "Which language would you like to use the app in?",
    continueBtn        = "Continue",

    dailyInspiration = "Daily Inspiration",
    todayTasks       = "Today's Tasks",
    streak           = "Streak",
    consecutive      = "Consecutive",
    recordLabel      = "Record",
    detailsArrow     = "Details →",
    todayMood        = "Today's Mood",
    selectMoodHint   = "How are you feeling today?",
    changeMood       = "✏️  Change",
    moodBad          = "Bad",
    moodOk           = "Okay",
    moodGood         = "Good",
    moodGreat        = "Great",
    moodSuper        = "Amazing!",

    newTask          = "New Task",
    taskNameHint     = "Task name *",
    taskNameRequired = "Name is required!",
    categoryLabel    = "Category",
    priorityLabel    = "Priority",
    priorityLow      = "Low",
    priorityMedium   = "Medium",
    priorityHigh     = "High",
    noTasks          = "No tasks for today",
    noTasksHint      = "Add a task using the + button",
    taskCategories   = listOf("Work", "Personal", "Health", "Education", "Other"),
    taskDone         = "completed",

    notesTitle      = "Notes",
    searchNotes     = "Search notes...",
    newNote         = "New Note",
    noteTitleHint   = "Title (optional)...",
    noteContentHint = "Write your thoughts...",
    noteColors      = "Note color",
    pinnedLabel     = "Pinned",
    noNotes         = "No notes yet",
    noNotesHint     = "Add your first note using the FAB",

    settingsTitle          = "Settings",
    darkMode               = "Dark Mode",
    darkModeOn             = "Dark background",
    darkModeOff            = "Light background",
    resetStreak            = "Reset Streak",
    resetStreakCurrent     = "Current",
    resetStreakConfirmTitle = "Reset Streak",
    resetStreakConfirmBody  = "will be deleted. This action cannot be undone.",
    resetStreakConfirmYes   = "Yes, reset",
    resetStreakConfirmNo    = "Cancel",
    streakReset            = "Streak reset ✓",
    versionLabel           = "Version",
    developerLabel         = "Developer",
    minAndroidLabel        = "Min. Android version",
    currentStreakLabel     = "Current streak",
    recordStreakLabel      = "Record streak",
    languageLabel          = "Language",
    languageChangeDesc     = "App language",

    statistics        = "Statistics",
    weeklyResults     = "This week's results",
    weeklyMood        = "Weekly Mood",
    noMoodYet         = "No mood tracked yet. Set it from the Home screen!",
    overallStats      = "Overall Statistics",
    weeklyTasks       = "Weekly Tasks",
    weeklyHabits      = "Weekly Habits",
    noStats           = "No statistics yet",
    noStatsHint       = "Add a habit or task to see data here",
    streakAndActivity = "Streak & Activity",
    lastSevenDays     = "Last 7 Days",
    ketmaKet          = "Consecutive",
    rekord            = "Record",
    weeklyTaskActivity = "Weekly Task Activity",
    habitTracker      = "Habit Tracker",

    totalTasksLabel        = "Total tasks",
    completionPctLabel     = "Completion %",
    activeHabitsLabel      = "Active habits",
    longestHabitStreakLabel = "Longest habit streak",
    allLabel               = "total",
    activeLabel            = "active",
    averageLabel           = "average",
    dayAbbreviations       = listOf("Mo", "Tu", "We", "Th", "Fr", "Sa", "Su")
)

// ── CompositionLocal + extension ──────────────────────────────────────────────

val LocalAppStrings = staticCompositionLocalOf { uzStrings }

val MaterialTheme.strings: AppStrings
    @Composable
    @ReadOnlyComposable
    get() = LocalAppStrings.current
